# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: node:16

pipelines:
    default:
        - step:
              name: "Install dependencies"
              caches:
                  - node
              script:
                  - yarn install
        - parallel:
              - step:
                    name: "Typescript"
                    caches:
                        - node
                    script:
                        - yarn run build-ts
              - step:
                    name: "Lint"
                    caches:
                        - node
                    script:
                        - yarn lint
