# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: node:16

pipelines:
  default:
    - parallel:
      - step:
          name: 'Install dependencies'
          caches:
            - node
          script:
            - npm install
      - step:
          name: 'Lint'
          caches:
            - node
          script:
            - npm lint

